#!/bin/sh
#
# Copyright (C) 2001-2004 Graeme Walker <graeme_walker@users.sourceforge.net>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later
# version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# ===
#
# xar
#
# A replacement for 'ar' that does 'CC -xar' ignoring 
# autoconf's bogus "cru" switches.
#
# For example:
# $ chmod +x lib/sunpro5/xar
# $ ./configure --enable-whatever AR=`pwd`/lib/sunpro5/xar
#
CC="CC" 
if test -x "${CXX}" ; then CC="${CXX}" ; fi
if test "${1}" = "--cxx" ; then CC="${2}" ; shift ; shift ; fi
shift # get rid of "cru" flags
exec ${CC} -xar -o "$@"
