.\" Copyright (C) 2001-2013 Graeme Walker <graeme_walker@users.sourceforge.net>
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH EMAILRELAY-PASSWD 1 local
.SH NAME
emailrelay-passwd \- a password encoding utility for E-MailRelay
.SH SYNOPSIS
.B emailrelay-passwd
.SH DESCRIPTION
.I emailrelay-passwd
is a utility which reads a single plaintext password from the standard
input, and writes out an encoded form onto the standard
output. The encoded form is suitable for pasting into a CRAM-MD5
line in an
.B emailrelay
secrets file.
.LP
A secrets file containing two CRAM-MD5 passwords might look like
this:
.LP
#
.br
# emailrelay.auth
.br
#
.br
server cram-md5 bob 1465267825.1002706143.2005162520.2739353706.4126076156.3423185672.2674269368.3056934447
.br
server cram-md5 alice 4039336516.3719314525.4148590512.4209236927.1897255360.1012201638.2279588408.1076355329
.br
.SH SEE ALSO
.BR emailrelay (1),
.BR emailrelay-submit (1),
.BR emailrelay-poke (1)
.br
.B RFC2104
.br
.B RFC2195
.SH AUTHOR
Graeme Walker, mailto:graeme_walker@users.sourceforge.net
