.\" Copyright (C) 2001-2013 Graeme Walker <graeme_walker@users.sourceforge.net>
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH EMAILRELAY 1 local
.SH NAME
emailrelay \- e-mail transfer agent and proxy
.SH SYNOPSIS
.B emailrelay
[OPTIONS]
.LP
.B emailrelay
--as-server
.LP
.B emailrelay
--as-client
.I server-address
.LP
.B emailrelay
--as-proxy
.I server-address
.SH DESCRIPTION
.I emailrelay
is a simple SMTP proxy and store-and-forward message transfer agent.
It does store-and-forward mail relay to a fixed next-hop server, without
any routing.
.LP
It runs in two main modes: a storage daemon
.RI ( --as-server )
and a forwarding
agent
.RI ( --as-client ).
The storage daemon is an SMTP server which stores e-mail
messages in a local spool directory. The forwarding agent acts as an
SMTP client sending the spooled e-mail messages on to the next
SMTP server in the chain.
.LP
It can also run in a third mode, as a proxy server
.RI ( --as-proxy ).
In this mode all messages are forwarded immediately to the next-hop
server. Messages are only fully accepted from the sender once they
have been successfully delivered to the next-hop server.
.SH OPTIONS
.TP
.B \-a, --admin \fI<admin-port>\fR
Enables the administration interface and specifies its listening port number.
.TP
.B \-Q, --admin-terminate 
Enables the terminate command on the admin interface.
.TP
.B \-A, --anonymous 
Disables the smtp vrfy command and sends less verbose smtp responses.
.TP
.B \-q, --as-client \fI<host:port>\fR
Runs as a client, forwarding all spooled mail to <host>: equivalent to \fI--log\fR \fI--no-syslog\fR \fI--no-daemon\fR \fI--dont-serve\fR \fI--forward\fR \fI--forward-to\fR.
.TP
.B \-y, --as-proxy \fI<host:port>\fR
Runs as a proxy server, forwarding each mail immediately to <host>: equivalent to \fI--log\fR \fI--close-stderr\fR \fI--poll\fR=0 \fI--forward-to\fR.
.TP
.B \-d, --as-server 
Runs as a server, storing mail in the spool directory: equivalent to \fI--log\fR \fI--close-stderr\fR.
.TP
.B \-C, --client-auth \fI<file>\fR
Enables smtp authentication with the remote server, using the given secrets file.
.TP
.B \-Y, --client-filter \fI<program>\fR
Specifies an external program to process messages when they are forwarded.
.TP
.B \-j, --client-tls 
Enables negotiated tls/ssl for smtp client (if openssl built in).
.TP
.B \-b, --client-tls-connection 
Enables smtp over tls/ssl for smtp client (if openssl built in).
.TP
.B \-e, --close-stderr 
Closes the standard error stream soon after start-up.
.TP
.B \-U, --connection-timeout \fI<time>\fR
Sets the timeout (in seconds) when connecting to a remote server (default is 40).
.TP
.B \-g, --debug 
Generates debug-level logging if built in.
.TP
.B \-D, --domain \fI<fqdn>\fR
Sets an override for the host's fully qualified domain name.
.TP
.B \-x, --dont-serve 
Disables acting as a server on any port (part of \fI--as-client\fR and usually used with \fI--forward\fR).
.TP
.B \-z, --filter \fI<program>\fR
Specifies an external program to process messages as they are stored.
.TP
.B \-W, --filter-timeout \fI<time>\fR
Sets the timeout (in seconds) for running the \fI--filter\fR processor (default is 300).
.TP
.B \-f, --forward 
Forwards stored mail on startup (requires \fI--forward-to\fR).
.TP
.B \-o, --forward-to \fI<host:port>\fR
Specifies the remote smtp server (required by \fI--forward\fR, \fI--poll\fR, \fI--immediate\fR and \fI--admin\fR).
.TP
.B \-h, --help 
Displays help text and exits.
.TP
.B \-m, --immediate 
Enables immediate forwarding of messages as soon as they are received (requires \fI--forward-to\fR).
.TP
.B \-I, --interface \fI<ip-list>\fR
Defines the listening interface(s) for incoming connections (comma-separated list with optional smtp=,pop=,admin= qualifiers).
.TP
.B \-l, --log 
Writes log information on standard error and syslog (but see \fI--close-stderr\fR and \fI--no-syslog\fR).
.TP
.B \-L, --log-time 
Adds a timestamp to the logging output.
.TP
.B \-t, --no-daemon 
Does not detach from the terminal.
.TP
.B \-X, --no-smtp 
Disables listening for smtp connections (usually used with \fI--admin\fR or \fI--pop\fR).
.TP
.B \-n, --no-syslog 
Disables syslog output (always overridden by \fI--syslog\fR).
.TP
.B \-i, --pid-file \fI<pid-file>\fR
Defines a file for storing the daemon process-id.
.TP
.B \-O, --poll \fI<period>\fR
Enables polling of the spool directory for messages to be forwarded with the specified period (zero means on client disconnection) (requires \fI--forward-to\fR).
.TP
.B \-B, --pop 
Enables the pop server.
.TP
.B \-F, --pop-auth \fI<file>\fR
Defines the pop server secrets file (default is \fI/etc/emailrelay.auth\fR).
.TP
.B \-J, --pop-by-name 
Modifies the pop spool directory according to the pop user name (requires \fI--pop\fR).
.TP
.B \-G, --pop-no-delete 
Disables message deletion via pop (requires \fI--pop\fR).
.TP
.B \-E, --pop-port \fI<port>\fR
Specifies the pop listening port number (default is 110) (requires \fI--pop\fR).
.TP
.B \-p, --port \fI<port>\fR
Specifies the smtp listening port number (default is 25).
.TP
.B \-w, --prompt-timeout \fI<time>\fR
Sets the timeout (in seconds) for getting an initial prompt from the server (default is 20).
.TP
.B \-r, --remote-clients 
Allows remote clients to connect.
.TP
.B \-T, --response-timeout \fI<time>\fR
Sets the response timeout (in seconds) when talking to a remote server (default is 1800).
.TP
.B \-S, --server-auth \fI<file>\fR
Enables authentication of remote clients, using the given secrets file.
.TP
.B \-K, --server-tls \fI<pem-file>\fR
Enables negotiated tls/ssl for smtp server using the given openssl certificate file (which must be in the directory trusted by openssl).
.TP
.B \-M, --size \fI<bytes>\fR
Limits the size of submitted messages.
.TP
.B \-s, --spool-dir \fI<dir>\fR
Specifies the spool directory (default is \fI/var/spool/emailrelay\fR).
.TP
.B \-k, --syslog 
Forces syslog output if logging is enabled (overrides \fI--no-syslog\fR).
.TP
.B \-0, --tls-config \fI<flags>\fR
Sets tls configuration flags (eg. 2 for SSLv2 support).
.TP
.B \-u, --user \fI<username>\fR
Names the effective user to switch to if started as root (default is \fIdaemon\fR).
.TP
.B \-v, --verbose 
Generates more verbose output (works with \fI--help\fR and \fI--log\fR).
.TP
.B \-Z, --verifier \fI<program>\fR
Specifies an external program for address verification.
.TP
.B \-V, --version 
Displays version information and exits.
.SH FILES
GNU style...
.br
/usr/local/etc/emailrelay.conf
.br
/usr/local/etc/emailrelay.conf.template
.br
/usr/local/etc/pam.d/emailrelay
.br
/usr/local/libexec/emailrelay/emailrelay-filter-copy
.br
/usr/local/libexec/emailrelay/emailrelay-poke
.br
/usr/local/libexec/emailrelay/examples/*
.br
/usr/local/libexec/emailrelay/init/emailrelay
.br
/usr/local/man/man1/emailrelay*.1.gz
.br
/usr/local/sbin/emailrelay
.br
/usr/local/sbin/emailrelay-passwd
.br
/usr/local/sbin/emailrelay-submit
.br
/usr/local/share/emailrelay/doc/*
.br
/usr/local/share/emailrelay/doc/index.html
.br
/usr/local/share/emailrelay/doc/README
.br
/usr/local/var/spool/emailrelay/emailrelay.*.content
.br
/usr/local/var/spool/emailrelay/emailrelay.*.envelope
.LP
FHS style...
.br
/etc/emailrelay.conf
.br
/etc/init.d/emailrelay
.br
/etc/pam.d/emailrelay
.br
/usr/lib/emailrelay/emailrelay-filter-copy
.br
/usr/lib/emailrelay/emailrelay-poke
.br
/usr/lib/emailrelay/examples/*
.br
/usr/sbin/emailrelay
.br
/usr/sbin/emailrelay-passwd
.br
/usr/sbin/emailrelay-submit
.br
/usr/share/doc/emailrelay/*
.br
/usr/share/doc/emailrelay/index.html
.br
/usr/share/doc/emailrelay/README
.br
/usr/share/man/man1/emailrelay*.1.gz
.br
/var/spool/emailrelay/emailrelay.*.content
.br
/var/spool/emailrelay/emailrelay.*.envelope
.SH SEE ALSO
E-MailRelay user guide, http://emailrelay.sourceforge.net/userguide.html .
.br
E-MailRelay reference, http://emailrelay.sourceforge.net/reference.html .
.br
.BR emailrelay-submit (1),
.BR emailrelay-passwd (1),
.SH AUTHOR
Graeme Walker, mailto:graeme_walker@users.sourceforge.net
